"""
Report Generator Module
Exports match results and candidate evaluation reports into Markdown, JSON, and PDF formats.
"""

import io
import json
from typing import Dict, Any

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


def generate_markdown_report(analysis_results: Dict[str, Any]) -> str:
    """Creates a comprehensive markdown summary report."""
    score = analysis_results.get('overall_score', 0)
    tier = analysis_results.get('match_tier', 'N/A')
    predicted_role = analysis_results.get('predicted_category', 'Software Engineering')
    skills_info = analysis_results.get('skills_analysis', {})
    ats_info = analysis_results.get('ats_audit', {})

    matched = ", ".join(skills_info.get('matched_skills', [])) or "None"
    missing = ", ".join(skills_info.get('missing_skills', [])) or "None"
    additional = ", ".join(skills_info.get('additional_skills', [])) or "None"

    report = f"""# AI Resume Analysis & Job Match Report

**Generated on:** System Date  
**Overall Match Score:** {score}%  
**Match Tier:** {tier}  
**Predicted Optimal Career Domain:** {predicted_role}  

---

## 1. Score Breakdown
- **Skill Match Overlap:** {analysis_results.get('score_breakdown', {}).get('skill_match_score', 0)}% (Weight: 45%)
- **TF-IDF & NLP Semantic Similarity:** {analysis_results.get('score_breakdown', {}).get('tfidf_cosine_score', 0)}% (Weight: 35%)
- **Experience Alignment:** {analysis_results.get('score_breakdown', {}).get('experience_score', 0)}% (Weight: 10%)
- **Education Alignment:** {analysis_results.get('score_breakdown', {}).get('education_score', 0)}% (Weight: 10%)

---

## 2. Skills Analysis
- **Matching Skills ({len(skills_info.get('matched_skills', []))}):**  
  {matched}

- **Missing / Gap Skills ({len(skills_info.get('missing_skills', []))}):**  
  {missing}

- **Additional Skills Found ({len(skills_info.get('additional_skills', []))}):**  
  {additional}

---

## 3. ATS Health & Resume Audit
- **ATS Overall Score:** {ats_info.get('overall_ats_score', 'N/A')}/100
- **Word Count:** {ats_info.get('word_count', 0)} ({ats_info.get('length_status', '')})
- **Action Verbs Count:** {ats_info.get('action_verbs_count', 0)}
- **Quantifiable Achievements:** {ats_info.get('quantifiable_metrics_count', 0)} found

### Improvement Suggestions:
"""
    for sug in ats_info.get('improvement_suggestions', []):
        report += f"- {sug}\n"

    report += "\n---\n*Report generated by AI Resume Analyzer & Job Match Predictor.*"
    return report


def generate_pdf_report(analysis_results: Dict[str, Any]) -> bytes:
    """Generates a styled PDF report in bytes buffer using ReportLab."""
    if not HAS_REPORTLAB:
        # Fallback return plain text in bytes
        return generate_markdown_report(analysis_results).encode('utf-8')

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1E3A8A'),
        spaceAfter=10
    )
    h2_style = ParagraphStyle(
        'Heading2',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1F2937'),
        spaceBefore=12,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'Body',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#374151')
    )

    story = []
    
    # Title
    story.append(Paragraph("<b>AI Resume Analysis & Job Match Report</b>", title_style))
    story.append(Paragraph(f"<b>Overall Match Score:</b> {analysis_results.get('overall_score', 0)}% &nbsp;|&nbsp; <b>Rating:</b> {analysis_results.get('match_tier', '')} &nbsp;|&nbsp; <b>Predicted Domain:</b> {analysis_results.get('predicted_category', '')}", body_style))
    story.append(Spacer(1, 12))

    # Score Table
    score_data = [
        ["Metric", "Score", "Weight"],
        ["Skill Match Overlap", f"{analysis_results.get('score_breakdown', {}).get('skill_match_score', 0)}%", "45%"],
        ["TF-IDF Cosine Similarity", f"{analysis_results.get('score_breakdown', {}).get('tfidf_cosine_score', 0)}%", "35%"],
        ["Experience Alignment", f"{analysis_results.get('score_breakdown', {}).get('experience_score', 0)}%", "10%"],
        ["Education Alignment", f"{analysis_results.get('score_breakdown', {}).get('education_score', 0)}%", "10%"],
        ["Overall Match Score", f"{analysis_results.get('overall_score', 0)}%", "100%"]
    ]
    t = Table(score_data, colWidths=[240, 150, 150])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#EEF2F6')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#1E293B')),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#F8FAFC')),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold')
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # Skills Section
    skills_info = analysis_results.get('skills_analysis', {})
    story.append(Paragraph("<b>Skills Breakdown</b>", h2_style))
    
    matched = ", ".join(skills_info.get('matched_skills', [])) or "None identified"
    missing = ", ".join(skills_info.get('missing_skills', [])) or "None identified"
    
    story.append(Paragraph(f"<b>✓ Matched Skills ({len(skills_info.get('matched_skills', []))}):</b> {matched}", body_style))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>✗ Missing / Gap Skills ({len(skills_info.get('missing_skills', []))}):</b> {missing}", body_style))
    story.append(Spacer(1, 12))

    # ATS Audit Section
    ats_info = analysis_results.get('ats_audit', {})
    story.append(Paragraph("<b>ATS & Resume Health Audit</b>", h2_style))
    story.append(Paragraph(f"<b>Overall ATS Score:</b> {ats_info.get('overall_ats_score', 0)}/100 &nbsp;|&nbsp; <b>Word Count:</b> {ats_info.get('word_count', 0)} ({ats_info.get('length_status', '')})", body_style))
    story.append(Spacer(1, 6))

    suggestions = ats_info.get('improvement_suggestions', [])
    if suggestions:
        story.append(Paragraph("<b>Key Suggestions for Improvement:</b>", body_style))
        for sug in suggestions:
            story.append(Paragraph(f"• {sug}", body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
